## Array

In [1]:
import numpy as np

In [10]:
l = [10,20,30,40.9,50,60]
print(l)
print(type(l))
arr = np.array(l)
print(arr)
print(type(arr))


[10, 20, 30, 40.9, 50, 60]
<class 'list'>
[10.  20.  30.  40.9 50.  60. ]
<class 'numpy.ndarray'>


In [6]:
print(arr)

[10 20 30 40 50 60]


In [5]:
print(l)

[10, 20, 30, 40, 50, 60]


In [11]:
l1 = [[10,20,30,40,50,60],[10,20,30,40,50,60],[10,20,120,40,50,60],[10,20,30,40,50,60],[10,20,30,40,50,60]]  # 2X2 2-d array

print(l1)
print(type(l1))
arr1 = np.array(l1)
arr1

[[10, 20, 30, 40, 50, 60], [10, 20, 30, 40, 50, 60], [10, 20, 120, 40, 50, 60], [10, 20, 30, 40, 50, 60], [10, 20, 30, 40, 50, 60]]
<class 'list'>


array([[ 10,  20,  30,  40,  50,  60],
       [ 10,  20,  30,  40,  50,  60],
       [ 10,  20, 120,  40,  50,  60],
       [ 10,  20,  30,  40,  50,  60],
       [ 10,  20,  30,  40,  50,  60]])

In [17]:
arr1[2][0:3]

array([ 10,  20, 120])

In [4]:
### 3 X 2 array--> 3 rows and 2 columns

In [5]:
l2 = [  [[10,20,30,40,50,60],[10,20,30,40,50,60],[10,20,30,40,50,60],[10,20,30,40,50,60],[10,20,30,40,50,60]],[[10,20,30,40,50,60],[10,20,30,40,50,60],[10,20,30,40,50,60],[10,20,30,40,50,60],[10,20,30,40,50,60]],[[10,20,30,40,50,60],[10,20,30,40,50,60],[10,20,30,40,50,60],[10,20,30,40,50,60],[10,20,30,40,50,60]],[[10,20,30,40,50,60],[10,20,30,40,50,60],[10,20,30,40,50,60],[10,20,30,40,50,60],[10,20,30,40,50,60]]  ]
arr2 = np.array(l2)
arr2

array([[[10, 20, 30, 40, 50, 60],
        [10, 20, 30, 40, 50, 60],
        [10, 20, 30, 40, 50, 60],
        [10, 20, 30, 40, 50, 60],
        [10, 20, 30, 40, 50, 60]],

       [[10, 20, 30, 40, 50, 60],
        [10, 20, 30, 40, 50, 60],
        [10, 20, 30, 40, 50, 60],
        [10, 20, 30, 40, 50, 60],
        [10, 20, 30, 40, 50, 60]],

       [[10, 20, 30, 40, 50, 60],
        [10, 20, 30, 40, 50, 60],
        [10, 20, 30, 40, 50, 60],
        [10, 20, 30, 40, 50, 60],
        [10, 20, 30, 40, 50, 60]],

       [[10, 20, 30, 40, 50, 60],
        [10, 20, 30, 40, 50, 60],
        [10, 20, 30, 40, 50, 60],
        [10, 20, 30, 40, 50, 60],
        [10, 20, 30, 40, 50, 60]]])

In [6]:
### 4 X 5 array--->   4 rows and 5 columns

In [4]:
l3 = [[10,11,12,13.98,14],[15,16,17,18,19],[20,21,22,23,24],[25,26,27,28,29]]
arr3 = np.array(l3)
arr3

array([[10.  , 11.  , 12.  , 13.98, 14.  ],
       [15.  , 16.  , 17.  , 18.  , 19.  ],
       [20.  , 21.  , 22.  , 23.  , 24.  ],
       [25.  , 26.  , 27.  , 28.  , 29.  ]])

In [2]:
import numpy as np   #Importing the library

In [3]:
weights=["adf","sdfg","asdf",56]
a = np.array(weights)
a

array(['adf', 'sdfg', 'asdf', '56'], dtype='<U21')

## Random

In [4]:
np.random.rand(80)    #random number from uniform distribution i.e[0,1)

array([0.83302948, 0.32275409, 0.33104639, 0.60410932, 0.00262006,
       0.38031142, 0.17292157, 0.53862512, 0.92839344, 0.46706375,
       0.44722691, 0.13294601, 0.0321323 , 0.66372938, 0.08408764,
       0.6170395 , 0.07590717, 0.99089789, 0.98810402, 0.35814489,
       0.68568836, 0.00883346, 0.29245772, 0.16811893, 0.1260505 ,
       0.1663008 , 0.64060777, 0.92115244, 0.97138866, 0.59325782,
       0.29365619, 0.20738119, 0.56698203, 0.66528144, 0.61635399,
       0.04776052, 0.11226095, 0.61892858, 0.66522765, 0.83969895,
       0.02575289, 0.19422221, 0.94249028, 0.00767403, 0.16799323,
       0.71901022, 0.6993268 , 0.34427509, 0.99654739, 0.82739155,
       0.7350616 , 0.62778153, 0.89004331, 0.21836289, 0.32300943,
       0.54579823, 0.3058165 , 0.03408804, 0.55857845, 0.31042788,
       0.41800002, 0.45160554, 0.77197488, 0.65148918, 0.77169132,
       0.08915789, 0.03086294, 0.62665598, 0.99677454, 0.43885705,
       0.62384367, 0.16075915, 0.36224842, 0.19730748, 0.71106

In [7]:
a=np.random.rand(2,6,4)  #array---->shape(row,columns)
a

array([[[0.84243006, 0.55459318, 0.07706711, 0.03768488],
        [0.0200329 , 0.00673359, 0.20430571, 0.01244933],
        [0.02550531, 0.84775347, 0.22487854, 0.89599547],
        [0.70938702, 0.63129002, 0.19613871, 0.04191861],
        [0.07288244, 0.11843242, 0.60590582, 0.17333323],
        [0.20602131, 0.42538745, 0.2129191 , 0.01599716]],

       [[0.4565668 , 0.39557925, 0.24366204, 0.5331273 ],
        [0.00492054, 0.1246197 , 0.26515613, 0.81586232],
        [0.48041668, 0.728023  , 0.05958557, 0.44317002],
        [0.95807796, 0.16999646, 0.48680562, 0.40617365],
        [0.50976303, 0.87284692, 0.81270753, 0.09544041],
        [0.69890955, 0.68112991, 0.61762464, 0.49624304]]])

In [12]:
np.random.rand(1,5)

array([[0.19558029, 0.98425321, 0.16074184, 0.9182285 , 0.10034725]])

In [11]:
np.random.randn(3,5,4)    # random number from standard normal distribution i.e[-3,3)

array([[[-0.2142498 , -2.04058991, -0.83453873, -0.38954179],
        [-1.05590094,  0.4349441 ,  0.02361491, -1.33402697],
        [ 0.99726842,  1.49271243,  0.80285703, -1.62327708],
        [ 0.40620869, -1.58262077,  0.23934063, -0.09742096],
        [-0.89216715,  0.42908772, -0.07461248,  0.35724403]],

       [[-0.77877056,  0.15585518, -0.03600309, -2.32267879],
        [-0.89250004,  0.08636207, -1.08700775,  0.47891005],
        [ 1.71410277,  0.44256122,  1.05065402, -0.2686791 ],
        [ 0.62157019,  0.00376674, -0.42400264,  0.50808631],
        [-1.29154811, -0.784283  , -1.38477868, -0.34275531]],

       [[ 1.16772139, -1.56404445,  0.8990229 , -0.1456746 ],
        [-0.46253021, -0.77820721, -0.09434094, -1.37905783],
        [-1.15137192, -0.44036707, -0.59701401, -0.39376488],
        [ 0.74121411,  0.15985049, -1.6894255 , -0.12772448],
        [ 0.67721652,  0.63095457,  3.12172945,  0.68522816]]])

In [14]:
a=np.random.randn(2,4)  #array---->shape(row,columns)
a

array([[-1.06408475,  0.14507414,  1.3085339 ,  0.20696161],
       [ 0.65582608, -0.20385585,  0.88626415,  0.84251751]])

In [18]:
np.random.randint(100)   ## generates randm int between [0,100)

35

In [16]:
## generate a rand number between 50 -100

In [21]:
np.random.randint(50,100)    # generates a random number btw [50,100)

61

In [18]:
## generate an array with 10 elements with random number between 1,100

In [23]:
np.random.randint(1,100,80)

array([20,  3, 17, 39, 99, 52, 79, 61, 51, 23, 36,  1, 35, 25, 47, 65, 51,
       73, 95, 93, 59, 62, 16, 62, 21, 73, 83, 14, 21,  9, 26, 96, 60, 67,
       25, 76, 57, 30,  1, 59, 18, 98, 71, 85, 53,  8, 20, 34, 48, 27, 29,
       46, 20, 11, 46,  1, 50, 55, 15, 52, 76, 49, 31, 56, 12,  6, 18,  1,
       59, 81, 29, 38, 50, 59, 88, 18, 78, 68, 94, 10], dtype=int32)

In [20]:
## generate a 5X5 array elements with random number between 1,100

In [27]:
np.random.randint(1,100,(5,5))

array([[97, 73, 84, 11, 15],
       [36, 81, 16, 98, 77],
       [88, 58, 15, 31, 36],
       [40, 22, 51, 75, 74],
       [73, 11, 48, 96, 98]], dtype=int32)

In [28]:
np.random.randint(1,100,[5,5,6])

array([[[85, 47, 70, 39, 89, 59],
        [21, 12, 40, 90, 67, 61],
        [38, 13, 70, 32, 79, 86],
        [89, 61, 26, 16, 75, 39],
        [25, 14, 65,  5, 70, 78]],

       [[24, 74, 98, 35, 79, 42],
        [97, 81, 83, 63, 93,  9],
        [25, 86, 24,  7, 39, 13],
        [84, 72, 72, 63, 35, 64],
        [22, 13,  3, 32, 30, 53]],

       [[ 7, 72, 29, 80, 44, 80],
        [75, 98, 78,  4, 48, 91],
        [51, 91, 30, 78, 71, 91],
        [10, 83, 27, 72, 61, 48],
        [94,  4, 97, 32, 79, 75]],

       [[49, 59, 89,  1, 57, 91],
        [10, 12, 25, 30, 97, 93],
        [38, 45, 52, 89, 67, 40],
        [48, 65, 91,  2,  5, 29],
        [46, 99, 70, 89, 98, 11]],

       [[10, 36, 33, 61, 78, 80],
        [52, 64, 78, 78, 89,  6],
        [65, 15, 11, 65, 71, 85],
        [36, 70, 31,  7, 80, 86],
        [75, 93, 21, 94, 85, 71]]], dtype=int32)

In [23]:
#np.random.randint(low, high, size, dtype])    returns a random integer

In [24]:
np.random.randint(9)    #if high is not mentioned then returns random number between 0(inclusive) to 9(excluseive)

4

In [30]:
np.random.randint(1,10)   #returns /random number between 1(inclusive) to 10(exclusive)

6

In [55]:
np.random.randint(1,100,5)

array([91,  9, 84, 64, 49], dtype=int32)

In [29]:
np.random.seed(8)
np.random.randint(1,100)

68

In [28]:
np.random.seed(100)
np.random.randint(10)

8

In [29]:
np.random.seed(1000)       #method is used to initialize the random number generator.
np.random.randint(9)

3

In [30]:
np.random.seed(1000)       #method is used to initialize the random number generator.
np.random.randint(90)

51

## Arange

In [32]:
for i in range(0,10):
    print(i)

a = np.arange(1,10,2) # returns an array with elements starting from 0 up untill 10 [0,10)

print(a)

0
1
2
3
4
5
6
7
8
9
[1 3 5 7 9]


In [32]:
#  arange(start,stop,step)

In [33]:
import numpy as np
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a=np.arange(0,10)

print(a)
b=np.arange(10,20)

print(b)
a>b
# np.logical_and(a,b)# returns an array of number in the range of [0,10)# returns an array of number in the range of [0,10)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


array([False, False, False, False, False, False, False, False, False,
       False])

np.arange(start,stop,step)

In [37]:
np.arange(0,10,4)

array([0, 4, 8])

### Linspace

In [59]:
np.random.randint(1,10,20)

array([6, 2, 4, 3, 3, 7, 9, 4, 5, 6, 6, 8, 3, 7, 6, 2, 7, 5, 6, 9],
      dtype=int32)

In [40]:
np.linspace(1,10,25,retstep=True)   # divedes data in equal specified parts

(array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
         4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
         7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
        10.   ]),
 np.float64(0.375))

In [37]:
np.linspace(1,100,4,retstep=True)   # not used 

(array([  1.,  34.,  67., 100.]), np.float64(33.0))

In [38]:
np.arange(0,16,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [39]:
a=np.random.randint(1,10000,10)
for i in a:
    if i %2==0:
        print(i,'even')
    else:
        print(i,'odd')

4696 even
6216 even
3777 odd
2399 odd
9565 odd
770 even
7809 odd
3630 even
5994 even
2397 odd


## Identity Matrix

In [40]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [41]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [44]:
np.eye(5,k=-2,dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [43]:
np.eye(5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [68]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [45]:
np.zeros(40)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [75]:
a=np.zeros([4,5,6])

print(a+4)

[[[4. 4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4. 4.]]

 [[4. 4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4. 4.]]

 [[4. 4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4. 4.]]

 [[4. 4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4. 4.]]]


In [47]:
np.ones(4)

array([1., 1., 1., 1.])

In [72]:
np.full((8,9),fill_value=9)

array([[9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9]])

## Attributes of array

In [49]:
arr1=np.arange(1,20)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [50]:
arr1=np.arange(1,20)
arr1.size                     # returns the number of elements in the array

19

In [76]:
arr2=np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
arr2.size            

12

In [52]:
arr1=np.arange(1,20)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [53]:
arr1=np.arange(1,20)
arr1.shape                    # returns the shape of array  number of rows and columns in array

(19,)

In [54]:
arr2=np.array([[1,2],
               [3,4],
               [5,6]])
arr2.shape                          #returns the shape i.e (row,columns)

(3, 2)

In [77]:
arr2=np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
arr2.shape

(2, 3, 2)

In [55]:
arr1=np.arange(1,20)
arr1.ndim                                    # returns the dimensions of the array

1

In [78]:
arr2=np.array([[1,2],[3,4],[5,6]])
arr2.ndim

2

In [56]:
arr2=np.array([[[1,2],[3,4],[3,4]],[[1,2],[3,4],[3,4]]])
arr2.ndim                                 

3

In [57]:
arr1=np.arange(1,20)
arr1.dtype                            #returns the dtype of elements

dtype('int64')

In [58]:
arr1=np.arange(1,5,0.5)
arr1.dtype   

dtype('float64')

In [59]:
### create an array with even number between 1,20
### create a 2X2 identity martix
### Create an array with any random 10 number

In [60]:
np.arange(0,20,(4,5))

TypeError: unsupported operand type(s) for /: 'int' and 'tuple'

In [ ]:
np.eye(2)

In [61]:
np.random.randint(100,size=10)

array([91, 36, 60, 42, 58, 41, 20, 30, 88, 30], dtype=int32)

## Reshape

In [29]:
import numpy as np
l= np.arange(1,13)

l.reshape(1,12)     # reshapes the data in (row,columns)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [63]:
l= np.arange(1,11)
l.reshape(5,2)        

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [64]:
## create an 5X 5 matrix using arange

In [65]:
import numpy as np
l = np.arange(1,26)
l=l.reshape(1,25)
print(l)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25]]


## Indexing

In [19]:
import numpy as np

# l= np.array([1,2,3,4,5,6])

l= np.array([[[1,2,3,4,5,6,7],
             [11,12,13,14,15,16,17],
             [21,22,23,24,25,26,27]],
           [[31,32,33,34,35,36,37],
             [41,42,43,44,45,46,47],
             [51,52,53,54,55,56,57]]])
l

array([[[ 1,  2,  3,  4,  5,  6,  7],
        [11, 12, 13, 14, 15, 16, 17],
        [21, 22, 23, 24, 25, 26, 27]],

       [[31, 32, 33, 34, 35, 36, 37],
        [41, 42, 43, 44, 45, 46, 47],
        [51, 52, 53, 54, 55, 56, 57]]])

In [24]:
l[1][0][3]

np.int64(34)

In [27]:
l[-1]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [11, 12, 13, 14, 15, 16, 17],
       [21, 22, 23, 24, 25, 26, 27]])

1. Create a 5X5 matrix with even numbers statrting from 2

2. Create an array of all 1's of size 10. Multiply 10 to all elements on even index and 5 to all elements on odd index

In [48]:
l1=np.arange(2,51,2)
l1.size

25

In [30]:
b=[1,2,3,5,4,5]
b[::2]

[1, 3, 4]

In [150]:
a=np.ones(10)
a[::2]=a[::2]*10
a[1::2]=a[1::2]*5
print(a)

[10.  5. 10.  5. 10.  5. 10.  5. 10.  5.]


In [90]:
a=np.arange(2,52,2)
a.reshape(5,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

## Slicing

In [29]:
l=np.arange(10,20)
l

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [30]:
l[2:9:2]

array([12, 14, 16, 18])

In [31]:
l[0:4]

array([10, 11, 12, 13])

In [32]:
l=np.arange(1,26).reshape(5,5)
l
# l.ravel()

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [145]:
l[0][3]

np.int64(4)

In [34]:
l[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [143]:
l[2:3,3:4]

array([[14]])

In [129]:
l[0:2,0:4]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [146]:
l[0:2,3:]

array([[ 4,  5],
       [ 9, 10]])

In [149]:
l[:,0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
## Display the last two rows
## display the first column
## display the second column
## display the last two columns

In [103]:
l[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [104]:
l[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [105]:
l[0:,0]

array([ 1,  6, 11, 16, 21])

In [106]:
l[0:,1]

array([ 2,  7, 12, 17, 22])

In [8]:
l[0:,-2:]
l.ravel()

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

## Comparison operations

In [21]:
import numpy as np
l=np.arange(1,10)
l

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
l!=5

array([ True,  True,  True,  True, False,  True,  True,  True,  True])

In [4]:
l>=5

array([False, False, False, False,  True,  True,  True,  True,  True])

In [53]:
l[l>=5]    ## filters data based on the condition

array([5, 6, 7, 8, 9])

In [54]:
l[l<=7]

array([1, 2, 3, 4, 5, 6, 7])

## Arithmetic operations

### Addition

In [4]:

import numpy as np
arr1=np.array([[10,20,30,40,50,70],[10,20,30,40,50,70]])
arr2=np.array([[1,2,3,4,5,50],[1,2,3,4,5,50]])
arr1,arr2

(array([[10, 20, 30, 40, 50, 70],
        [10, 20, 30, 40, 50, 70]]),
 array([[ 1,  2,  3,  4,  5, 50],
        [ 1,  2,  3,  4,  5, 50]]))

In [5]:
arr1+arr2

array([[ 11,  22,  33,  44,  55, 120],
       [ 11,  22,  33,  44,  55, 120]])

### Subtraction

In [12]:
arr1*arr2

array([  10,   40,   90,  160,  250, 3500])

### Multiplication

In [11]:
arr1 // arr2

array([10, 10, 10, 10, 10,  1])

### Dot Product

In [14]:
a=np.arange(1,5).reshape(2,2)
b=np.arange(1,5).reshape(2,2)
a,b

(array([[1, 2],
        [3, 4]]),
 array([[1, 2],
        [3, 4]]))

In [15]:
np.dot(a,b)

array([[ 7, 10],
       [15, 22]])

### Min

In [16]:
a

array([[1, 2],
       [3, 4]])

In [17]:
np.min(a)

np.int64(1)

### Max

In [18]:
np.max(a)

np.int64(4)

### Sum

In [19]:
np.sum(a)

np.int64(10)

### Mean

In [20]:
np.mean(a)

np.float64(2.5)

### Square

In [21]:
np.square(a)

array([[ 1,  4],
       [ 9, 16]])

### Power

In [22]:
np.power(a,5)

array([[   1,   32],
       [ 243, 1024]])

## Transpose

In [68]:
a

array([[1, 2],
       [3, 4]])

In [69]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

## Concat   1D AND 2D

In [25]:
a=np.array([1,2,3])
b=np.array([4,5,6])
[a,b]

[array([1, 2, 3]), array([4, 5, 6])]

In [8]:
np.concatenate(a,b)   # not valid

TypeError: only integer scalar arrays can be converted to a scalar index

In [11]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
arr=np.concatenate((a,b,c))
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[5,6],[7,8],[6,7]])
a,b

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[5, 6],
        [7, 8],
        [6, 7]]))

In [7]:
### axis=0---> rows
### axis=1--->columns

In [9]:
np.concatenate((a,b),axis=0)   #increase number of rows


array([[1, 2],
       [3, 4],
       [5, 6],
       [5, 6],
       [7, 8],
       [6, 7]])

In [74]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
arr=np.concatenate((a,b),axis=0)   #increase number of rows

In [75]:
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.array([[5,6],[7,8]])
arr=np.concatenate((a,b,c),axis=1)   #increase number of columns

In [89]:
arr

array([[1, 2, 5, 6, 5, 6],
       [3, 4, 7, 8, 7, 8]])

## Stack

In [10]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])
a3 = np.array([[5,6],[7,8]])

In [11]:
a1

array([[1, 2],
       [3, 4]])

In [12]:
a2

array([[5, 6],
       [7, 8]])

In [13]:
a3

array([[5, 6],
       [7, 8]])

In [14]:
np.hstack((a1,a2,a3)) ## concatenate axis = 1   #increase number of columns

array([[1, 2, 5, 6, 5, 6],
       [3, 4, 7, 8, 7, 8]])

In [15]:
np.dstack((a1,a2)) ## concatenate axis = 0  #increase number of rows

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [37]:
np.vstack((a1,a2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [5, 6],
       [7, 8]])

## Split

In [17]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
np.split(arr,[1,4,7])

[array([0]), array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [45]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.array_split(arr,6) # total%n = 0  ---> Perfect split  total%n != 0 ----> Added to the first

[array([0, 1]),
 array([2, 3]),
 array([4, 5]),
 array([6]),
 array([7]),
 array([8])]

In [5]:
arr2 = np.arange(25).reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
np.split(arr2,(2,4))

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]])]

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
np.split(arr,(2,5)) ## specify the cuts at index 2 and index 5

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8])]

In [24]:
import numpy as np
np.split(arr,3) ## error as the 3 equal sized splits are not possible

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [11]:
arr = np.arange(24).reshape(6,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
np.hsplit(arr,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16],
        [20]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17],
        [21]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18],
        [22]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23]])]

In [147]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
np.vsplit(arr,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [15]:
arr = np.arange(12).reshape(3,2,2)
arr

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [13]:
import numpy as np
a=np.array([[[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]],[[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]]])


# print(a)

# ,[1,2,3,4,5,6,7,8,9]],[[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]]

#   3    3
for i in a:
    for j in i:
        for k in j:
            print(k)

    
    
    
# print(a[0])
# print(a[1])

1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9


In [24]:
import numpy as np
a=np.array([[10,20,30,40],[50,60,70,80]])

for i in a:
    print(i)
    
# print(a[0])
# print(a[1])


[10 20 30 40]
[50 60 70 80]


## Iterating an array

In [150]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [151]:
np.array_split(arr,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
det = np.linalg.det(A)
print("Determinant:", det)


Determinant: -2.0000000000000004


In [2]:
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)


Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [3]:
v = np.array([3, 4])
norm = np.linalg.norm(v)
print("Vector Norm:", norm)

Vector Norm: 5.0


In [4]:
import numpy as np

# Original feature: age in years
age = np.array([20, 30, 40])
# Feature engineering: age squared
age_squared = np.power(age, 2)
print("Age Squared:", age_squared)


Age Squared: [ 400  900 1600]


In [5]:
ones = np.ones((3, 2))
print("Ones array:\n", ones)

Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
filled = np.full((2, 2), 7)
print("Full array:\n", filled)

Full array:
 [[7 7]
 [7 7]]
